export const countryList = [
    {
        label: 'Afghanistan',
        value: 'Afghanistan',
        dialCode: '+93',
        short: 'AF',
    },
    {
        label: 'Aland Islands',
        value: 'Aland Islands',
        dialCode: '+358',
        short: 'AX',
    },
    {
        label: 'Albania',
        value: 'Albania',
        dialCode: '+355',
        short: 'AL',
    },
    {
        label: 'Algeria',
        value: 'Algeria',
        dialCode: '+213',
        short: 'DZ',
    },
    {
        label: 'AmericanSamoa',
        value: 'AmericanSamoa',
        dialCode: '+1684',
        short: 'AS',
    },
    {
        label: 'Andorra',
        value: 'Andorra',
        dialCode: '+376',
        short: 'AD',
    },
    {
        label: 'Angola',
        value: 'Angola',
        dialCode: '+244',
        short: 'AO',
    },
    {
        label: 'Anguilla',
        value: 'Anguilla',
        dialCode: '+1264',
        short: 'AI',
    },
    {
        label: 'Antarctica',
        value: 'Antarctica',
        dialCode: '+672',
        short: 'AQ',
    },
    {
        label: 'Antigua and Barbuda',
        value: 'Antigua and Barbuda',
        dialCode: '+1268',
        short: 'AG',
    },
    {
        label: 'Argentina',
        value: 'Argentina',
        dialCode: '+54',
        short: 'AR',
    },
    {
        label: 'Armenia',
        value: 'Armenia',
        dialCode: '+374',
        short: 'AM',
    },
    {
        label: 'Aruba',
        value: 'Aruba',
        dialCode: '+297',
        short: 'AW',
    },
    {
        label: 'Australia',
        value: 'Australia',
        dialCode: '+61',
        short: 'AU',
    },
    {
        label: 'Austria',
        value: 'Austria',
        dialCode: '+43',
        short: 'AT',
    },
    {
        label: 'Azerbaijan',
        value: 'Azerbaijan',
        dialCode: '+994',
        short: 'AZ',
    },
    {
        label: 'Bahamas',
        value: 'Bahamas',
        dialCode: '+1242',
        short: 'BS',
    },
    {
        label: 'Bahrain',
        value: 'Bahrain',
        dialCode: '+973',
        short: 'BH',
    },
    {
        label: 'Bangladesh',
        value: 'Bangladesh',
        dialCode: '+880',
        short: 'BD',
    },
    {
        label: 'Barbados',
        value: 'Barbados',
        dialCode: '+1246',
        short: 'BB',
    },
    {
        label: 'Belarus',
        value: 'Belarus',
        dialCode: '+375',
        short: 'BY',
    },
    {
        label: 'Belgium',
        value: 'Belgium',
        dialCode: '+32',
        short: 'BE',
    },
    {
        label: 'Belize',
        value: 'Belize',
        dialCode: '+501',
        short: 'BZ',
    },
    {
        label: 'Benin',
        value: 'Benin',
        dialCode: '+229',
        short: 'BJ',
    },
    {
        label: 'Bermuda',
        value: 'Bermuda',
        dialCode: '+1441',
        short: 'BM',
    },
    {
        label: 'Bhutan',
        value: 'Bhutan',
        dialCode: '+975',
        short: 'BT',
    },
    {
        label: 'Bolivia, Plurinational State of',
        value: 'Bolivia, Plurinational State of',
        dialCode: '+591',
        short: 'BO',
    },
    {
        label: 'Bosnia and Herzegovina',
        value: 'Bosnia and Herzegovina',
        dialCode: '+387',
        short: 'BA',
    },
    {
        label: 'Botswana',
        value: 'Botswana',
        dialCode: '+267',
        short: 'BW',
    },
    {
        label: 'Brazil',
        value: 'Brazil',
        dialCode: '+55',
        short: 'BR',
    },
    {
        label: 'British Indian Ocean Territory',
        value: 'British Indian Ocean Territory',
        dialCode: '+246',
        short: 'IO',
    },
    {
        label: 'Brunei Darussalam',
        value: 'Brunei Darussalam',
        dialCode: '+673',
        short: 'BN',
    },
    {
        label: 'Bulgaria',
        value: 'Bulgaria',
        dialCode: '+359',
        short: 'BG',
    },
    {
        label: 'Burkina Faso',
        value: 'Burkina Faso',
        dialCode: '+226',
        short: 'BF',
    },
    {
        label: 'Burundi',
        value: 'Burundi',
        dialCode: '+257',
        short: 'BI',
    },
    {
        label: 'Cambodia',
        value: 'Cambodia',
        dialCode: '+855',
        short: 'KH',
    },
    {
        label: 'Cameroon',
        value: 'Cameroon',
        dialCode: '+237',
        short: 'CM',
    },
    {
        label: 'Canada',
        value: 'Canada',
        dialCode: '+1 ',
        short: 'CA',
    },
    {
        label: 'Cape Verde',
        value: 'Cape Verde',
        dialCode: '+238',
        short: 'CV',
    },
    {
        label: 'Cayman Islands',
        value: 'Cayman Islands',
        dialCode: '+ 345',
        short: 'KY',
    },
    {
        label: 'Central African Republic',
        value: 'Central African Republic',
        dialCode: '+236',
        short: 'CF',
    },
    {
        label: 'Chad',
        value: 'Chad',
        dialCode: '+235',
        short: 'TD',
    },
    {
        label: 'Chile',
        value: 'Chile',
        dialCode: '+56',
        short: 'CL',
    },
    {
        label: 'China',
        value: 'China',
        dialCode: '+86',
        short: 'CN',
    },
    {
        label: 'Christmas Island',
        value: 'Christmas Island',
        dialCode: '+61',
        short: 'CX',
    },
    {
        label: 'Cocos (Keeling) Islands',
        value: 'Cocos (Keeling) Islands',
        dialCode: '+61',
        short: 'CC',
    },
    {
        label: 'Colombia',
        value: 'Colombia',
        dialCode: '+57',
        short: 'CO',
    },
    {
        label: 'Comoros',
        value: 'Comoros',
        dialCode: '+269',
        short: 'KM',
    },
    {
        label: 'Congo',
        value: 'Congo',
        dialCode: '+242',
        short: 'CG',
    },
    {
        label: 'Congo, The Democratic Republic of the Congo',
        value: 'Congo, The Democratic Republic of the Congo',
        dialCode: '+243',
        short: 'CD',
    },
    {
        label: 'Cook Islands',
        value: 'Cook Islands',
        dialCode: '+682',
        short: 'CK',
    },
    {
        label: 'Costa Rica',
        value: 'Costa Rica',
        dialCode: '+506',
        short: 'CR',
    },
    {
        label: "Cote d'Ivoire",
        value: "Cote d'Ivoire",
        dialCode: '+225',
        short: 'CI',
    },
    {
        label: 'Croatia',
        value: 'Croatia',
        dialCode: '+385',
        short: 'HR',
    },
    {
        label: 'Cuba',
        value: 'Cuba',
        dialCode: '+53',
        short: 'CU',
    },
    {
        label: 'Cyprus',
        value: 'Cyprus',
        dialCode: '+357',
        short: 'CY',
    },
    {
        label: 'Czech Republic',
        value: 'Czech Republic',
        dialCode: '+420',
        short: 'CZ',
    },
    {
        label: 'Denmark',
        value: 'Denmark',
        dialCode: '+45',
        short: 'DK',
    },
    {
        label: 'Djibouti',
        value: 'Djibouti',
        dialCode: '+253',
        short: 'DJ',
    },
    {
        label: 'Dominica',
        value: 'Dominica',
        dialCode: '+1767',
        short: 'DM',
    },
    {
        label: 'Dominican Republic',
        value: 'Dominican Republic',
        dialCode: '+1849',
        short: 'DO',
    },
    {
        label: 'Ecuador',
        value: 'Ecuador',
        dialCode: '+593',
        short: 'EC',
    },
    {
        label: 'Egypt',
        value: 'Egypt',
        dialCode: '+20',
        short: 'EG',
    },
    {
        label: 'El Salvador',
        value: 'El Salvador',
        dialCode: '+503',
        short: 'SV',
    },
    {
        label: 'Equatorial Guinea',
        value: 'Equatorial Guinea',
        dialCode: '+240',
        short: 'GQ',
    },
    {
        label: 'Eritrea',
        value: 'Eritrea',
        dialCode: '+291',
        short: 'ER',
    },
    {
        label: 'Estonia',
        value: 'Estonia',
        dialCode: '+372',
        short: 'EE',
    },
    {
        label: 'Ethiopia',
        value: 'Ethiopia',
        dialCode: '+251',
        short: 'ET',
    },
    {
        label: 'Falkland Islands (Malvinas)',
        value: 'Falkland Islands (Malvinas)',
        dialCode: '+500',
        short: 'FK',
    },
    {
        label: 'Faroe Islands',
        value: 'Faroe Islands',
        dialCode: '+298',
        short: 'FO',
    },
    {
        label: 'Fiji',
        value: 'Fiji',
        dialCode: '+679',
        short: 'FJ',
    },
    {
        label: 'Finland',
        value: 'Finland',
        dialCode: '+358',
        short: 'FI',
    },
    {
        label: 'France',
        value: 'France',
        dialCode: '+33',
        short: 'FR',
    },
    {
        label: 'French Polynesia',
        value: 'French Polynesia',
        dialCode: '+689',
        short: 'PF',
    },
    {
        label: 'Gabon',
        value: 'Gabon',
        dialCode: '+241',
        short: 'GA',
    },
    {
        label: 'Gambia',
        value: 'Gambia',
        dialCode: '+220',
        short: 'GM',
    },
    {
        label: 'Georgia',
        value: 'Georgia',
        dialCode: '+995',
        short: 'GE',
    },
    {
        label: 'Germany',
        value: 'Germany',
        dialCode: '+49',
        short: 'DE',
    },
    {
        label: 'Ghana',
        value: 'Ghana',
        dialCode: '+233',
        short: 'GH',
    },
    {
        label: 'Gibraltar',
        value: 'Gibraltar',
        dialCode: '+350',
        short: 'GI',
    },
    {
        label: 'Greece',
        value: 'Greece',
        dialCode: '+30',
        short: 'GR',
    },
    {
        label: 'Greenland',
        value: 'Greenland',
        dialCode: '+299',
        short: 'GL',
    },
    {
        label: 'Grenada',
        value: 'Grenada',
        dialCode: '+1473',
        short: 'GD',
    },
    {
        label: 'Guam',
        value: 'Guam',
        dialCode: '+1671',
        short: 'GU',
    },
    {
        label: 'Guatemala',
        value: 'Guatemala',
        dialCode: '+502',
        short: 'GT',
    },
    {
        label: 'Guernsey',
        value: 'Guernsey',
        dialCode: '+44',
        short: 'GG',
    },
    {
        label: 'Guinea',
        value: 'Guinea',
        dialCode: '+224',
        short: 'GN',
    },
    {
        label: 'Guinea-Bissau',
        value: 'Guinea-Bissau',
        dialCode: '+245',
        short: 'GW',
    },
    {
        label: 'Guyana',
        value: 'Guyana',
        dialCode: '+595',
        short: 'GY',
    },
    {
        label: 'Haiti',
        value: 'Haiti',
        dialCode: '+509',
        short: 'HT',
    },
    {
        label: 'Holy See (Vatican City State)',
        value: 'Holy See (Vatican City State)',
        dialCode: '+379',
        short: 'VA',
    },
    {
        label: 'Honduras',
        value: 'Honduras',
        dialCode: '+504',
        short: 'HN',
    },
    {
        label: 'Hong Kong',
        value: 'Hong Kong',
        dialCode: '+852',
        short: 'HK',
    },
    {
        label: 'Hungary',
        value: 'Hungary',
        dialCode: '+36',
        short: 'HU',
    },
    {
        label: 'Iceland',
        value: 'Iceland',
        dialCode: '+354',
        short: 'IS',
    },
    {
        label: 'India',
        value: 'India',
        dialCode: '+91',
        short: 'IN',
    },
    {
        label: 'Indonesia',
        value: 'Indonesia',
        dialCode: '+62',
        short: 'ID',
    },
    {
        label: 'Iran, Islamic Republic of Persian Gulf',
        value: 'Iran, Islamic Republic of Persian Gulf',
        dialCode: '+98',
        short: 'IR',
    },
    {
        label: 'Iraq',
        value: 'Iraq',
        dialCode: '+964',
        short: 'IQ',
    },
    {
        label: 'Ireland',
        value: 'Ireland',
        dialCode: '+353',
        short: 'IE',
    },
    {
        label: 'Isle of Man',
        value: 'Isle of Man',
        dialCode: '+44',
        short: 'IM',
    },
    {
        label: 'Israel',
        value: 'Israel',
        dialCode: '+972',
        short: 'IL',
    },
    {
        label: 'Italy',
        value: 'Italy',
        dialCode: '+39',
        short: 'IT',
    },
    {
        label: 'Jamaica',
        value: 'Jamaica',
        dialCode: '+1876',
        short: 'JM',
    },
    {
        label: 'Japan',
        value: 'Japan',
        dialCode: '+81',
        short: 'JP',
    },
    {
        label: 'Jersey',
        value: 'Jersey',
        dialCode: '+44',
        short: 'JE',
    },
    {
        label: 'Jordan',
        value: 'Jordan',
        dialCode: '+962',
        short: 'JO',
    },
    {
        label: 'Kazakhstan',
        value: 'Kazakhstan',
        dialCode: '+77',
        short: 'KZ',
    },
    {
        label: 'Kenya',
        value: 'Kenya',
        dialCode: '+254',
        short: 'KE',
    },
    {
        label: 'Kiribati',
        value: 'Kiribati',
        dialCode: '+686',
        short: 'KI',
    },
    {
        label: "Korea, Democratic People's Republic of Korea",
        value: "Korea, Democratic People's Republic of Korea",
        dialCode: '+850',
        short: 'KP',
    },
    {
        label: 'Korea, Republic of South Korea',
        value: 'Korea, Republic of South Korea',
        dialCode: '+82',
        short: 'KR',
    },
    {
        label: 'Kuwait',
        value: 'Kuwait',
        dialCode: '+965',
        short: 'KW',
    },
    {
        label: 'Kyrgyzstan',
        value: 'Kyrgyzstan',
        dialCode: '+996',
        short: 'KG',
    },
    {
        label: 'Laos',
        value: 'Laos',
        dialCode: '+856',
        short: 'LA',
    },
    {
        label: 'Latvia',
        value: 'Latvia',
        dialCode: '+371',
        short: 'LV',
    },
    {
        label: 'Lebanon',
        value: 'Lebanon',
        dialCode: '+961',
        short: 'LB',
    },
    {
        label: 'Lesotho',
        value: 'Lesotho',
        dialCode: '+266',
        short: 'LS',
    },
    {
        label: 'Liberia',
        value: 'Liberia',
        dialCode: '+231',
        short: 'LR',
    },
    {
        label: 'Libyan Arab Jamahiriya',
        value: 'Libyan Arab Jamahiriya',
        dialCode: '+218',
        short: 'LY',
    },
    {
        label: 'Liechtenstein',
        value: 'Liechtenstein',
        dialCode: '+423',
        short: 'LI',
    },
    {
        label: 'Lithuania',
        value: 'Lithuania',
        dialCode: '+370',
        short: 'LT',
    },
    {
        label: 'Luxembourg',
        value: 'Luxembourg',
        dialCode: '+352',
        short: 'LU',
    },
    {
        label: 'Macao',
        value: 'Macao',
        dialCode: '+853',
        short: 'MO',
    },
    {
        label: 'Macedonia',
        value: 'Macedonia',
        dialCode: '+389',
        short: 'MK',
    },
    {
        label: 'Madagascar',
        value: 'Madagascar',
        dialCode: '+261',
        short: 'MG',
    },
    {
        label: 'Malawi',
        value: 'Malawi',
        dialCode: '+265',
        short: 'MW',
    },
    {
        label: 'Malaysia',
        value: 'Malaysia',
        dialCode: '+60',
        short: 'MY',
    },
    {
        label: 'Maldives',
        value: 'Maldives',
        dialCode: '+960',
        short: 'MV',
    },
    {
        label: 'Mali',
        value: 'Mali',
        dialCode: '+223',
        short: 'ML',
    },
    {
        label: 'Malta',
        value: 'Malta',
        dialCode: '+356',
        short: 'MT',
    },
    {
        label: 'Marshall Islands',
        value: 'Marshall Islands',
        dialCode: '+692',
        short: 'MH',
    },
    {
        label: 'Martinique',
        value: 'Martinique',
        dialCode: '+596',
        short: 'MQ',
    },
    {
        label: 'Mauritania',
        value: 'Mauritania',
        dialCode: '+222',
        short: 'MR',
    },
    {
        label: 'Mauritius',
        value: 'Mauritius',
        dialCode: '+230',
        short: 'MU',
    },
    {
        label: 'Mexico',
        value: 'Mexico',
        dialCode: '+52',
        short: 'MX',
    },
    {
        label: 'Micronesia, Federated States of Micronesia',
        value: 'Micronesia, Federated States of Micronesia',
        dialCode: '+691',
        short: 'FM',
    },
    {
        label: 'Moldova',
        value: 'Moldova',
        dialCode: '+373',
        short: 'MD',
    },
    {
        label: 'Monaco',
        value: 'Monaco',
        dialCode: '+377',
        short: 'MC',
    },
    {
        label: 'Mongolia',
        value: 'Mongolia',
        dialCode: '+976',
        short: 'MN',
    },
    {
        label: 'Montenegro',
        value: 'Montenegro',
        dialCode: '+382',
        short: 'ME',
    },
    {
        label: 'Montserrat',
        value: 'Montserrat',
        dialCode: '+1664',
        short: 'MS',
    },
    {
        label: 'Morocco',
        value: 'Morocco',
        dialCode: '+212',
        short: 'MA',
    },
    {
        label: 'Mozambique',
        value: 'Mozambique',
        dialCode: '+258',
        short: 'MZ',
    },
    {
        label: 'Myanmar',
        value: 'Myanmar',
        dialCode: '+95',
        short: 'MM',
    },
    {
        label: 'Namibia',
        value: 'Namibia',
        dialCode: '+264',
        short: 'NA',
    },
    {
        label: 'Nauru',
        value: 'Nauru',
        dialCode: '+674',
        short: 'NR',
    },
    {
        label: 'Nepal',
        value: 'Nepal',
        dialCode: '+977',
        short: 'NP',
    },
    {
        label: 'Netherlands',
        value: 'Netherlands',
        dialCode: '+31',
        short: 'NL',
    },
    {
        label: 'New Zealand',
        value: 'New Zealand',
        dialCode: '+64',
        short: 'NZ',
    },
    {
        label: 'Nicaragua',
        value: 'Nicaragua',
        dialCode: '+505',
        short: 'NI',
    },
    {
        label: 'Niger',
        value: 'Niger',
        dialCode: '+227',
        short: 'NE',
    },
    {
        label: 'Nigeria',
        value: 'Nigeria',
        dialCode: '+234',
        short: 'NG',
    },
    {
        label: 'Niue',
        value: 'Niue',
        dialCode: '+683',
        short: 'NU',
    },
    {
        label: 'Norfolk Island',
        value: 'Norfolk Island',
        dialCode: '+672',
        short: 'NF',
    },
    {
        label: 'Northern Mariana Islands',
        value: 'Northern Mariana Islands',
        dialCode: '+1670',
        short: 'MP',
    },
    {
        label: 'Norway',
        value: 'Norway',
        dialCode: '+47',
        short: 'NO',
    },
    {
        label: 'Oman',
        value: 'Oman',
        dialCode: '+968',
        short: 'OM',
    },
    {
        label: 'Pakistan',
        value: 'Pakistan',
        dialCode: '+92',
        short: 'PK',
    },
    {
        label: 'Palau',
        value: 'Palau',
        dialCode: '+680',
        short: 'PW',
    },
    {
        label: 'Palestinian Territory, Occupied',
        value: 'Palestinian Territory, Occupied',
        dialCode: '+970',
        short: 'PS',
    },
    {
        label: 'Panama',
        value: 'Panama',
        dialCode: '+507',
        short: 'PA',
    },
    {
        label: 'Papua New Guinea',
        value: 'Papua New Guinea',
        dialCode: '+675',
        short: 'PG',
    },
    {
        label: 'Paraguay',
        value: 'Paraguay',
        dialCode: '+595',
        short: 'PY',
    },
    {
        label: 'Peru',
        value: 'Peru',
        dialCode: '+51',
        short: 'PE',
    },
    {
        label: 'Philippines',
        value: 'Philippines',
        dialCode: '+63',
        short: 'PH',
    },
    {
        label: 'Pitcairn',
        value: 'Pitcairn',
        dialCode: '+872',
        short: 'PN',
    },
    {
        label: 'Poland',
        value: 'Poland',
        dialCode: '+48',
        short: 'PL',
    },
    {
        label: 'Portugal',
        value: 'Portugal',
        dialCode: '+351',
        short: 'PT',
    },
    {
        label: 'Puerto Rico',
        value: 'Puerto Rico',
        dialCode: '+1939',
        short: 'PR',
    },
    {
        label: 'Qatar',
        value: 'Qatar',
        dialCode: '+974',
        short: 'QA',
    },
    {
        label: 'Romania',
        value: 'Romania',
        dialCode: '+40',
        short: 'RO',
    },
    {
        label: 'Russia',
        value: 'Russia',
        dialCode: '+7',
        short: 'RU',
    },
    {
        label: 'Rwanda',
        value: 'Rwanda',
        dialCode: '+250',
        short: 'RW',
    },
    {
        label: 'Saint Barthelemy',
        value: 'Saint Barthelemy',
        dialCode: '+590',
        short: 'BL',
    },
    {
        label: 'Saint Kitts and Nevis',
        value: 'Saint Kitts and Nevis',
        dialCode: '+1869',
        short: 'KN',
    },
    {
        label: 'Saint Lucia',
        value: 'Saint Lucia',
        dialCode: '+1758',
        short: 'LC',
    },
    {
        label: 'Saint Vincent and the Grenadines',
        value: 'Saint Vincent and the Grenadines',
        dialCode: '+1784',
        short: 'VC',
    },
    {
        label: 'Samoa',
        value: 'Samoa',
        dialCode: '+685',
        short: 'WS',
    },
    {
        label: 'San Marino',
        value: 'San Marino',
        dialCode: '+378',
        short: 'SM',
    },
    {
        label: 'Sao Tome and Principe',
        value: 'Sao Tome and Principe',
        dialCode: '+239',
        short: 'ST',
    },
    {
        label: 'Saudi Arabia',
        value: 'Saudi Arabia',
        dialCode: '+966',
        short: 'SA',
    },
    {
        label: 'Senegal',
        value: 'Senegal',
        dialCode: '+221',
        short: 'SN',
    },
    {
        label: 'Serbia',
        value: 'Serbia',
        dialCode: '+381',
        short: 'RS',
    },
    {
        label: 'Seychelles',
        value: 'Seychelles',
        dialCode: '+248',
        short: 'SC',
    },
    {
        label: 'Sierra Leone',
        value: 'Sierra Leone',
        dialCode: '+232',
        short: 'SL',
    },
    {
        label: 'Singapore',
        value: 'Singapore',
        dialCode: '+65',
        short: 'SG',
    },
    {
        label: 'Slovakia',
        value: 'Slovakia',
        dialCode: '+421',
        short: 'SK',
    },
    {
        label: 'Slovenia',
        value: 'Slovenia',
        dialCode: '+386',
        short: 'SI',
    },
    {
        label: 'Solomon Islands',
        value: 'Solomon Islands',
        dialCode: '+677',
        short: 'SB',
    },
    {
        label: 'Somalia',
        value: 'Somalia',
        dialCode: '+252',
        short: 'SO',
    },
    {
        label: 'South Africa',
        value: 'South Africa',
        dialCode: '+27',
        short: 'ZA',
    },
    {
        label: 'South Sudan',
        value: 'South Sudan',
        dialCode: '+211',
        short: 'SS',
    },
    {
        label: 'Spain',
        value: 'Spain',
        dialCode: '+34',
        short: 'ES',
    },
    {
        label: 'Sri Lanka',
        value: 'Sri Lanka',
        dialCode: '+94',
        short: 'LK',
    },
    {
        label: 'Sudan',
        value: 'Sudan',
        dialCode: '+249',
        short: 'SD',
    },
    {
        label: 'Suriname',
        value: 'Suriname',
        dialCode: '+597',
        short: 'SR',
    },
    {
        label: 'Swaziland',
        value: 'Swaziland',
        dialCode: '+268',
        short: 'SZ',
    },
    {
        label: 'Sweden',
        value: 'Sweden',
        dialCode: '+46',
        short: 'SE',
    },
    {
        label: 'Switzerland',
        value: 'Switzerland',
        dialCode: '+41',
        short: 'CH',
    },
    {
        label: 'Syrian Arab Republic',
        value: 'Syrian Arab Republic',
        dialCode: '+963',
        short: 'SY',
    },
    {
        label: 'Taiwan',
        value: 'Taiwan',
        dialCode: '+886',
        short: 'TW',
    },
    {
        label: 'Tajikistan',
        value: 'Tajikistan',
        dialCode: '+992',
        short: 'TJ',
    },
    {
        label: 'Tanzania, United Republic of Tanzania',
        value: 'Tanzania, United Republic of Tanzania',
        dialCode: '+255',
        short: 'TZ',
    },
    {
        label: 'Thailand',
        value: 'Thailand',
        dialCode: '+66',
        short: 'TH',
    },
    {
        label: 'Timor-Leste',
        value: 'Timor-Leste',
        dialCode: '+670',
        short: 'TL',
    },
    {
        label: 'Togo',
        value: 'Togo',
        dialCode: '+228',
        short: 'TG',
    },
    {
        label: 'Tokelau',
        value: 'Tokelau',
        dialCode: '+690',
        short: 'TK',
    },
    {
        label: 'Tonga',
        value: 'Tonga',
        dialCode: '+676',
        short: 'TO',
    },
    {
        label: 'Trinidad and Tobago',
        value: 'Trinidad and Tobago',
        dialCode: '+1868',
        short: 'TT',
    },
    {
        label: 'Tunisia',
        value: 'Tunisia',
        dialCode: '+216',
        short: 'TN',
    },
    {
        label: 'Turkey',
        value: 'Turkey',
        dialCode: '+90',
        short: 'TR',
    },
    {
        label: 'Turkmenistan',
        value: 'Turkmenistan',
        dialCode: '+993',
        short: 'TM',
    },
    {
        label: 'Turks and Caicos Islands',
        value: 'Turks and Caicos Islands',
        dialCode: '+1649',
        short: 'TC',
    },
    {
        label: 'Tuvalu',
        value: 'Tuvalu',
        dialCode: '+688',
        short: 'TV',
    },
    {
        label: 'Uganda',
        value: 'Uganda',
        dialCode: '+256',
        short: 'UG',
    },
    {
        label: 'Ukraine',
        value: 'Ukraine',
        dialCode: '+380',
        short: 'UA',
    },
    {
        label: 'United Arab Emirates',
        value: 'United Arab Emirates',
        dialCode: '+971',
        short: 'AE',
    },
    {
        label: 'United Kingdom',
        value: 'United Kingdom',
        dialCode: '+44',
        short: 'GB',
    },
    {
        label: 'United States',
        value: 'United States',
        dialCode: '+1',
        short: 'US',
    },
    {
        label: 'Uruguay',
        value: 'Uruguay',
        dialCode: '+598',
        short: 'UY',
    },
    {
        label: 'Uzbekistan',
        value: 'Uzbekistan',
        dialCode: '+998',
        short: 'UZ',
    },
    {
        label: 'Vanuatu',
        value: 'Vanuatu',
        dialCode: '+678',
        short: 'VU',
    },
    {
        label: 'Venezuela, Bolivarian Republic of Venezuela',
        value: 'Venezuela, Bolivarian Republic of Venezuela',
        dialCode: '+58',
        short: 'VE',
    },
    {
        label: 'Vietnam',
        value: 'Vietnam',
        dialCode: '+84',
        short: 'VN',
    },
    {
        label: 'Virgin Islands, British',
        value: 'Virgin Islands, British',
        dialCode: '+1284',
        short: 'VG',
    },
    {
        label: 'Virgin Islands, U.S.',
        value: 'Virgin Islands, U.S.',
        dialCode: '+1340',
        short: 'VI',
    },
    {
        label: 'Yemen',
        value: 'Yemen',
        dialCode: '+967',
        short: 'YE',
    },
    {
        label: 'Zambia',
        value: 'Zambia',
        dialCode: '+260',
        short: 'ZM',
    },
    {
        label: 'Zimbabwe',
        value: 'Zimbabwe',
        dialCode: '+263',
        short: 'ZW',
    },
]
