export const currency = [
    { value: "BDT", label: "BDT" },
    { value: "USD", label: "USD" },
    { value: "EUR", label: "EUR" },
    { value: "GBP", label: "GBP" },
    { value: "JPY", label: "JPY" },
    { value: "CAD", label: "CAD" },
    { value: "AUD", label: "AUD" },
    { value: "CHF", label: "CHF" },
    { value: "CNY", label: "CNY" },
    { value: "HKD", label: "HKD" },
    { value: "NZD", label: "NZD" },
    { value: "SGD", label: "SGD" },
    { value: "SEK", label: "SEK" },
    { value: "NOK", label: "NOK" },
    { value: "DKK", label: "DKK" },
    { value: "BRL", label: "BRL" },
    { value: "INR", label: "INR" },
    { value: "RUB", label: "RUB" },
    { value: "ZAR", label: "ZAR" },
    { value: "MXN", label: "MXN" },
    { value: "KRW", label: "KRW" },
    { value: "TRY", label: "TRY" },
    { value: "AED", label: "AED" },
    { value: "HUF", label: "HUF" },
    { value: "PLN", label: "PLN" },
]